// Generated by gencpp from file radar/raw.msg
// DO NOT EDIT!


#ifndef RADAR_MESSAGE_RAW_H
#define RADAR_MESSAGE_RAW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar
{
template <class ContainerAllocator>
struct raw_
{
  typedef raw_<ContainerAllocator> Type;

  raw_()
    : data()
    , num(0)  {
    }
  raw_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , num(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;

   typedef uint64_t _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::radar::raw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar::raw_<ContainerAllocator> const> ConstPtr;

}; // struct raw_

typedef ::radar::raw_<std::allocator<void> > raw;

typedef boost::shared_ptr< ::radar::raw > rawPtr;
typedef boost::shared_ptr< ::radar::raw const> rawConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar::raw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar::raw_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace radar

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'radar': ['/home/project/cuav/realtime_radar_to_sar_img/catkin_ws/src/radar/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::radar::raw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar::raw_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar::raw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar::raw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar::raw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar::raw_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar::raw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a9dfb9a2c533f9dbe4573a54646cd9a";
  }

  static const char* value(const ::radar::raw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a9dfb9a2c533f9dULL;
  static const uint64_t static_value2 = 0xbe4573a54646cd9aULL;
};

template<class ContainerAllocator>
struct DataType< ::radar::raw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar/raw";
  }

  static const char* value(const ::radar::raw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar::raw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] data\n\
uint64 num\n\
";
  }

  static const char* value(const ::radar::raw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar::raw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct raw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar::raw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar::raw_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "num: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MESSAGE_RAW_H
