// Generated by gencpp from file radar/wav.msg
// DO NOT EDIT!


#ifndef RADAR_MESSAGE_WAV_H
#define RADAR_MESSAGE_WAV_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar
{
template <class ContainerAllocator>
struct wav_
{
  typedef wav_<ContainerAllocator> Type;

  wav_()
    : data()
    , num(0)  {
    }
  wav_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , num(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _data_type;
  _data_type data;

   typedef uint64_t _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::radar::wav_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar::wav_<ContainerAllocator> const> ConstPtr;

}; // struct wav_

typedef ::radar::wav_<std::allocator<void> > wav;

typedef boost::shared_ptr< ::radar::wav > wavPtr;
typedef boost::shared_ptr< ::radar::wav const> wavConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar::wav_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar::wav_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace radar

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'radar': ['/home/project/cuav/GUAVA/catkin_ws/src/radar/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::radar::wav_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar::wav_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar::wav_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar::wav_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar::wav_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar::wav_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar::wav_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee6398427bcac584a415147a410f1beb";
  }

  static const char* value(const ::radar::wav_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee6398427bcac584ULL;
  static const uint64_t static_value2 = 0xa415147a410f1bebULL;
};

template<class ContainerAllocator>
struct DataType< ::radar::wav_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar/wav";
  }

  static const char* value(const ::radar::wav_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar::wav_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] data\n\
uint64 num\n\
";
  }

  static const char* value(const ::radar::wav_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar::wav_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wav_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar::wav_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar::wav_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "num: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MESSAGE_WAV_H
